using SecureApp.Domain.Entities;
using SecureApp.Domain.ValueObjects;

namespace SecureApp.Domain.Interfaces.Services;

/// <summary>
/// Client for the community's shared, centrally-hosted (relay-side) file library — distinct from
/// a device's own local <see cref="Document"/> store. Files are encrypted client-side with a
/// symmetric key shared out-of-band across every device in the community (see
/// <c>KeyPurpose</c>-style vault key <c>"library:shared-key"</c>) before ever leaving the device,
/// so the relay only ever stores/serves ciphertext it cannot read — same trust boundary as
/// <c>IMessageTransport</c>'s relay.
/// </summary>
public interface ISharedLibraryService
{
    /// <summary>Whether this device already has the community's shared library key set up (generated or imported).</summary>
    Task<bool> HasSharedKeyAsync(CancellationToken ct = default);

    /// <summary>Generates a new shared library key on this device and returns it as a copyable blob for manual distribution to the rest of the community — same out-of-band pattern as a contact card.</summary>
    Task<string> GenerateSharedKeyAsync(CancellationToken ct = default);

    /// <summary>Imports a shared library key blob generated by another device.</summary>
    Task ImportSharedKeyAsync(string keyBlob, CancellationToken ct = default);

    Task<SharedLibraryFileSummary> UploadAsync(string folderPath, string fileName, IReadOnlyList<string> tags, Stream content, CancellationToken ct = default);

    /// <summary>Metadata-only search (file name, folder path, tag) — the relay never sees plaintext content, so it cannot search inside it either. All parameters are optional filters; omit all for "list everything".</summary>
    Task<IReadOnlyList<SharedLibraryFileSummary>> SearchAsync(string? query = null, string? folderPath = null, string? tag = null, CancellationToken ct = default);

    /// <summary>Downloads and decrypts a library file, then imports it as a normal local <see cref="Document"/> via the existing document-import path — so it becomes viewable through the already-built document viewer with no separate library-specific viewer needed.</summary>
    Task<Document> DownloadAndImportAsync(Guid libraryFileId, Guid? localFolderId = null, CancellationToken ct = default);

    Task DeleteAsync(Guid libraryFileId, CancellationToken ct = default);
}
