using SecureApp.Domain.Entities;
using SecureApp.Domain.ValueObjects;

namespace SecureApp.Domain.Interfaces.Services;

/// <summary>
/// Client for the community's shared, centrally-hosted (relay-side) file library — distinct from
/// a device's own local <see cref="Document"/> store. Files are encrypted client-side with a
/// symmetric key shared out-of-band across every device in the community (see
/// <c>KeyPurpose</c>-style vault key <c>"library:shared-key"</c>) before ever leaving the device,
/// so the relay only ever stores/serves ciphertext it cannot read — same trust boundary as
/// <c>IMessageTransport</c>'s relay.
/// </summary>
public interface ISharedLibraryService
{
    /// <summary>Whether this device already has the community's shared library key set up (generated or imported).</summary>
    Task<bool> HasSharedKeyAsync(CancellationToken ct = default);

    /// <summary>Generates a new shared library key on this device and returns it as a copyable blob for manual distribution to the rest of the community — same out-of-band pattern as a contact card.</summary>
    Task<string> GenerateSharedKeyAsync(CancellationToken ct = default);

    /// <summary>Imports a shared library key blob generated by another device.</summary>
    Task ImportSharedKeyAsync(string keyBlob, CancellationToken ct = default);

    /// <summary>
    /// Re-exports this device's already-stored shared library key as the same copyable blob
    /// <see cref="GenerateSharedKeyAsync"/> returns — for re-sharing with a device that missed it
    /// the first time, without minting a new key (which would desync this device from everyone
    /// who already imported the original). Throws if no key is stored yet.
    /// </summary>
    Task<string> ExportSharedKeyAsync(CancellationToken ct = default);

    /// <summary>Uploads an encrypted file. <paramref name="listed"/> = false marks it a PRIVATE chat attachment (2026-09-14): same encrypted storage, but hidden from the community library browser and reachable only by the id carried in the E2EE chat message. Default true = a normal community-library file.</summary>
    Task<SharedLibraryFileSummary> UploadAsync(string folderPath, string fileName, IReadOnlyList<string> tags, Stream content, bool listed = true, CancellationToken ct = default);

    /// <summary>Metadata-only search (file name, folder path, tag) — the relay never sees plaintext content, so it cannot search inside it either. All parameters are optional filters; omit all for "list everything".</summary>
    Task<IReadOnlyList<SharedLibraryFileSummary>> SearchAsync(string? query = null, string? folderPath = null, string? tag = null, CancellationToken ct = default);

    /// <summary>Downloads and decrypts a library file, then imports it as a normal local <see cref="Document"/> via the existing document-import path — so it becomes viewable through the already-built document viewer with no separate library-specific viewer needed.</summary>
    Task<Document> DownloadAndImportAsync(Guid libraryFileId, Guid? localFolderId = null, CancellationToken ct = default);

    Task DeleteAsync(Guid libraryFileId, CancellationToken ct = default);

    /// <summary>Promotes a private chat attachment to the community library (2026-09-14, 2.3 "move from local archive to global") — makes it browsable (relay is_listed=1), optionally in <paramref name="folderPath"/>. Uploader or admin only; idempotent for an already-listed file.</summary>
    Task PublishToLibraryAsync(Guid libraryFileId, string? folderPath = null, CancellationToken ct = default);

    /// <summary>
    /// Relay-mediated key escrow, push side (2026-09-11): if this device HAS the shared key, wraps it
    /// for every other community member (ML-KEM encapsulation to each member's published directory
    /// public key + AES-GCM) and uploads the per-recipient ciphertext to the relay. Fully automatic,
    /// no user action — called from the connection supervisor's periodic sweep and right after a key
    /// is generated/imported. Robust where the earlier peer-to-peer-over-the-chat-ratchet delivery was
    /// not: it needs neither a healthy pairwise session nor both devices online at once — the relay
    /// holds the wrapped key until the recipient next comes online. A no-op if this device has no key.
    /// The relay only ever stores ML-KEM ciphertext it cannot read.
    /// </summary>
    Task PublishWrappedKeyForMembersAsync(CancellationToken ct = default);

    /// <summary>
    /// Relay-mediated key escrow, pull side (2026-09-11): if this device does NOT have the shared key,
    /// fetches its own wrapped blob from the relay and unwraps it with this device's own private
    /// identity key, storing the recovered key. Returns true if a key was imported. A no-op (returns
    /// false) if this device already has the key or none has been escrowed for it yet.
    /// </summary>
    Task<bool> TryImportWrappedKeyAsync(CancellationToken ct = default);
}
